### ISSUE TITLE
Should be able to resize or expand the media browser

### ISSUE THREAD

**Issue by netpro2k** [MozillaReality/Spoke#566] opened 2019-04-26 00:12 UTC
Found the default size a bit tight. We could just make it bigger but I think you are going to want different sizes at different times so I would rather just be able to resize it (or at least expand it between 2 sizes)

**Comment by robertlong** [comment] 2019-04-26 22:01
Duplicate of #505

**Closed by robertlong** 2019-04-26 22:01 UTC
Labels: enhancement
