### ISSUE TITLE
Imported models should be centered on their origin

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/Spoke#212] opened 2018-09-13 01:14 UTC
The geometry of imported models can sometimes be offset from origin. We should probably use the bounding box to recenter them, probably with the bottom of the bounding box at origin.

**Comment by brianpeiris** [comment] 2018-09-21 02:16
I'm surprised no one brought this up during our testing.

**Comment by robertlong** [comment] 2018-09-28 15:50
I don't think you always want this. Some of our environments like the meeting room, require the original exported origin in order for them to line up to additional models. If the environment were exported in multiple pieces this would not be possible. Another example is the architecture kit models which use the original origin so that their rotation origin is set correctly.

**Comment by brianpeiris** [comment] 2018-10-09 21:18
Yup. Unfortunately default origins can be really incorrect for models from Google Poly especially. 

Maybe we could mark our gltf models with a special component to skip the auto recentering, or we give the user a button to recenter at will, or we make it an editor setting.

**Comment by robertlong** [comment] 2018-10-09 21:57
Because Google Poly doesn't handle scale correctly or center their models, maybe we can only apply this to models from that origin?

**Comment by robertlong** [comment] 2018-10-09 21:59
I agree, recentering an object to the center of its bonding box is a good feature though.

**Comment by brianpeiris** [comment] 2018-10-11 03:11
> Because Google Poly doesn't handle scale correctly or center their models, maybe we can only apply this to models from that origin?

This sounds like a reasonable solution for now.

**Comment by joshmarinacci** [comment] 2018-11-16 02:00
I'd be very happy with just a button next to the position fields in the property sheet

**Comment by robertlong** [comment] 2019-04-26 19:21
Marking as a duplicate of #382

**Closed by robertlong** 2019-04-26 19:21 UTC
