### ISSUE TITLE
Link to sketchfab model not loading

### ISSUE THREAD

**Issue by johnshaughnessy** [MozillaReality/Spoke#532] opened 2019-04-25 21:18 UTC
Nothing happens when I paste a sketchfab url into the "Model" field of a model element

![image](https://user-images.githubusercontent.com/4072106/56769046-ee111c00-6764-11e9-991c-225e6e971c9d.png)

**Comment by robertlong** [comment] 2019-04-26 22:33
Duplicate of #541

**Closed by robertlong** 2019-04-26 22:33 UTC
Labels: bug
