### ISSUE TITLE
Toolbar buttons should have tooltips

### ISSUE THREAD

**Issue by joshmarinacci** [MozillaReality/Spoke#305] opened 2018-10-03 23:20 UTC
There should be tooltips to explain what the toolbar buttons do, and their keyboard shortcuts.

<img width="292" alt="firefox nightlyscreensnapz051" src="https://user-images.githubusercontent.com/276938/46444728-35cc4980-c728-11e8-8a40-173332641f9a.png">

**Comment by robertlong** [comment] 2019-04-26 19:38
Duplicate of #167

**Closed by robertlong** 2019-04-26 19:38 UTC
Labels: enhancement
