### ISSUE TITLE
Binary release for MacOS doesn't work

### ISSUE THREAD

**Issue by joshmarinacci** [MozillaReality/Spoke#300] opened 2018-10-03 23:06 UTC
The 'spoke' executable doesn't have the executable bit set, so it tries to open in TextEdit. Once the bit is set manually it works fine.

**Comment by gfodor** [comment] 2018-10-04 16:47
assigned to @mquander feel free to kick back if this is non-trivial

**Comment by brianpeiris** [comment] 2018-10-04 18:32
Hmm, I fixed this for linux here: https://github.com/MozillaReality/Spoke/commit/e26b2df314aab5a64fb7ffe6edaf780fa00c7cea

Thought that would have worked for macOS as well, but I guess not.

**Comment by brianpeiris** [comment] 2018-10-06 02:38
I don't think we should expect users to run `chmod`, nor do I think we should delay the launch to build a real macOS bundle. 
I would rather reinstate https://github.com/MozillaReality/Spoke/commit/e26b2df314aab5a64fb7ffe6edaf780fa00c7cea

**Comment by brianpeiris** [comment] 2018-10-06 14:17
Hmm, actually I guess macOS bundles are just some zipped files with a .plist. Seems doable, but I'm not setup to test on macOS right now. I'll add zips back since it looks like we need that anyway. I think I need a zip with a package.json for the update mechanism anyway.

**Comment by brianpeiris** [comment] 2018-10-06 14:31
I've confirmed that Github strips the executable flag from bare executable in releases, so we need a zip for that reason as well.

**Comment by brianpeiris** [comment] 2018-10-06 15:11
Resolved in 7b764edacca7670a50d05b99a32ee0ebde19868b, I think. I'll need a mac user to test or I can do it later. Released in https://github.com/MozillaReality/Spoke/releases/tag/v1.0.0-rc.3

**Comment by mquander** [comment] 2018-10-07 01:39
Thanks, I agree that a zip file seems like a good compromise in this case.

**Comment by brianpeiris** [comment] 2018-10-08 20:58
Gonna reopen this. Apparently jszip doesn't produce executable flags that work on macOS. We could try https://github.com/thejoshwolfe/yazl or produce a `.tar.gz`

**Comment by robertlong** [comment] 2018-10-09 21:05
Fixed in 63f2d4796028207c13591045f8e7e1c29cadfa7f

**Closed by robertlong** 2018-10-09 21:06 UTC
Labels: bug
