### ISSUE TITLE
Can not change model src

### ISSUE THREAD

**Issue by netpro2k** [MozillaReality/Spoke#561] opened 2019-04-25 23:45 UTC
Throws an error:

```
14:12:41.497 TypeError: t is undefined[Learn More] ModelNodeEditor.js:19:24
    t ModelNodeEditor.js:19
    t LibraryInput.js:42
    React 12
    unstable_runWithPriority scheduler.production.min.js:18
    React 2
    Tn (index):1018
```

**Comment by robertlong** [comment] 2019-04-26 22:31
Duplicate of #541

**Closed by robertlong** 2019-04-26 22:31 UTC
Labels: bug
